class GhFilter < Formula
  desc "Allowlist shim for the gh CLI that refuses out-of-org invocations"
  homepage "https://github.com/happitec-inc/gh-filter"
  url "https://github.com/happitec-inc/gh-filter.git",
      tag:      "v0.2.1",
      revision: "06095e97bece013b6b8a34faef7b63b6ab0d2b6f"
  version "0.2.1"
  license "MIT"

  head "https://github.com/happitec-inc/gh-filter.git", branch: "main"

  depends_on "gh"

  # Design note: the real `gh` binary at #{Formula["gh"].opt_bin}/gh is
  # intentionally NOT replaced. Instead, we install gh-filter to libexec/
  # and create a separate `gh` shim in libexec/shim/ that the user opts
  # into by prepending #{opt_libexec}/shim to PATH. This keeps the gh
  # formula and the gh-filter formula fully independent — `brew upgrade gh`
  # cannot clobber the filter, and `brew upgrade gh-filter` cannot break
  # gh.
  def install
    libexec.install "gh-filter"

    (libexec/"shim").mkpath
    shim = libexec/"shim/gh"
    shim.write <<~SHIM
      #!/bin/bash
      # Auto-generated by the gh-filter formula. Execs the filter, which in
      # turn execs the real gh on allow.
      exec "#{opt_libexec}/gh-filter" "$@"
    SHIM
    chmod 0755, shim
  end

  def caveats
    <<~EOS
      gh-filter is installed but the `gh` shim is NOT yet active. The real
      gh binary at #{Formula["gh"].opt_bin}/gh remains untouched.

      To activate the filter, prepend the shim directory to PATH:

        echo 'export PATH="#{opt_libexec}/shim:$PATH"' >> ~/.zshrc

      Open a new shell (or `source ~/.zshrc`), then verify:

        which gh           # → #{opt_libexec}/shim/gh
        gh --version       # passes through real gh

      To test the filter actively blocks out-of-allowlist writes, try
      invoking it against a synthetic owner that is not in the allowlist:

        gh issue create --repo disallowed-test-owner/test-repo --title t --body b

      …should exit 77 with a verbose error and a Pushover alert.

      Configuration (environment variables):
        GH_FILTER_REAL_GH    Override the real gh binary path
                             (default: highest version in #{HOMEBREW_PREFIX}/Cellar/gh/)
        GH_FILTER_NOTIFY     Path to the `notify` binary (Pushover alerter)

      Allowed owners are baked into #{opt_libexec}/gh-filter (ALLOWED_OWNERS
      array near the top). Edit and `brew reinstall gh-filter` to change.

      Both formulas can be upgraded independently:
        `brew upgrade gh`         — does not touch gh-filter
        `brew upgrade gh-filter`  — does not touch the real gh binary
    EOS
  end

  test do
    assert_predicate libexec/"gh-filter", :executable?
    assert_predicate libexec/"shim/gh", :executable?

    # Pass-through: --version should reach the real gh and return its version.
    output = shell_output("#{libexec}/shim/gh --version")
    assert_match "gh version", output

    # Block path: a synthetic out-of-allowlist --repo should exit 77 with a
    # BLOCKED banner. We use a deliberately synthetic owner name to avoid
    # encoding any real third-party reference into the formula.
    # Silence the notify hook (test env has no Pushover binary).
    ENV["GH_FILTER_NOTIFY"] = "/usr/bin/true"
    output = shell_output("#{libexec}/gh-filter issue list --repo disallowed-test-owner/test-repo 2>&1", 77)
    assert_match "BLOCKED", output
    assert_match "disallowed-test-owner", output

    # Block path: api graphql is structurally refused.
    output = shell_output("#{libexec}/gh-filter api graphql 2>&1", 77)
    assert_match "graphql", output
  end
end
